allow-external-apps = true
disable-terminal-session-change-toast = true
terminal-cursor-style = bar
use-black-ui = true
terminal-margin-horizontal = 4
terminal-margin-vertical = 0

extra-keys = [ \
  ['LEFT', 'UP', 'DOWN', 'RIGHT'], \
  ['ESC', 'HOME', 'END', { macro: "CTRL L", display: "CLEAR" }], \
  ['TAB', 'CTRL', 'SHIFT', 'ALT'] \
]
